---
- hosts: localhost
  name: Volume Action
  vars:
    hostname: 192.168.0.101
    username: admin
    password: Netapp1!
    vserver: svm1
    aggr: aggr1
    vol_name: ansiblevol1
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: absent
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 20
      size_unit: gb
      policy: default
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
